#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("zup_subcategoria_queue")]
	public partial class zup_subcategoria_Queue : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the zup_subcategoria_queue entity
		/// </summary>
		public partial class Fields
		{
			public const string queueid = "queueid";
			public const string VersionNumber = "versionnumber";
			public const string zup_subcategoria_Queue_Queue = "zup_subcategoria_Queue_Queue";
			public const string zup_subcategoria_QueueId = "zup_subcategoria_queueid";
			public const string Id = "zup_subcategoria_queueid";
			public const string zup_subcategoriaid = "zup_subcategoriaid";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public zup_subcategoria_Queue(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public zup_subcategoria_Queue(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public zup_subcategoria_Queue(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public zup_subcategoria_Queue() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "zup_subcategoria_queueid";
		
		public const string EntitySchemaName = "zup_subcategoria_Queue";
		
		public const string EntityLogicalName = "zup_subcategoria_queue";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "zup_subcategoria_queueset";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		public System.Nullable<System.Guid> queueid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("queueid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("zup_subcategoria_queueid")]
		public System.Nullable<System.Guid> zup_subcategoria_QueueId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("zup_subcategoria_queueid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("zup_subcategoria_queueid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				base.Id = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("zup_subcategoriaid")]
		public System.Nullable<System.Guid> zup_subcategoriaid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("zup_subcategoriaid");
			}
		}
		
		/// <summary>
		/// N:N zup_subcategoria_Queue_Queue
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("zup_subcategoria_Queue_Queue")]
		public System.Collections.Generic.IEnumerable<DataverseModel.Queue> zup_subcategoria_Queue_Queue
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.Queue>("zup_subcategoria_Queue_Queue", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.Queue>("zup_subcategoria_Queue_Queue", null, value);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public zup_subcategoria_Queue(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["zup_subcategoria_queueid"] = base.Id;
                        break;
                    case "zup_subcategoria_queueid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
