#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AnalyzeSentiment")]
	public partial class AnalyzeSentimentRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string text = "text";
			public const string modelId = "modelId";
			public const string language = "language";
		}
		
		public const string ActionLogicalName = "AnalyzeSentiment";
		
		public string text
		{
			get
			{
				if (this.Parameters.Contains("text"))
				{
					return ((string)(this.Parameters["text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["text"] = value;
			}
		}
		
		public string modelId
		{
			get
			{
				if (this.Parameters.Contains("modelId"))
				{
					return ((string)(this.Parameters["modelId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["modelId"] = value;
			}
		}
		
		public string language
		{
			get
			{
				if (this.Parameters.Contains("language"))
				{
					return ((string)(this.Parameters["language"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["language"] = value;
			}
		}
		
		public AnalyzeSentimentRequest()
		{
			this.RequestName = "AnalyzeSentiment";
			this.text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AnalyzeSentiment")]
	public partial class AnalyzeSentimentResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string documentScores = "documentScores";
			public const string sentences = "sentences";
			public const string sentiment = "sentiment";
		}
		
		public const string ActionLogicalName = "AnalyzeSentiment";
		
		public AnalyzeSentimentResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity documentScores
		{
			get
			{
				if (this.Results.Contains("documentScores"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["documentScores"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["documentScores"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection sentences
		{
			get
			{
				if (this.Results.Contains("sentences"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["sentences"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["sentences"] = value;
			}
		}
		
		public string sentiment
		{
			get
			{
				if (this.Results.Contains("sentiment"))
				{
					return ((string)(this.Results["sentiment"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["sentiment"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
