#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Idiomas do Power Pages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum powerpagelanguages
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Alemão – Alemanha", 16, "#0000ff")]
		AlemOAlemanha = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Basco – Basco", 1, "#0000ff")]
		BascoBasco = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Búlgaro – Bulgária", 2, "#0000ff")]
		BLgaroBulgRia = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Catalão – Catalão", 3, "#0000ff")]
		CatalOCatalO = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cazaque – Cazaquistão", 24, "#0000ff")]
		CazaqueCazaquistO = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chinês – China", 4, "#0000ff")]
		ChinSChina = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chinês – RAE de Hong Kong", 5, "#0000ff")]
		ChinSRaeDeHongKong = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chinês – Tradicional", 6, "#0000ff")]
		ChinSTradicional = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Coreano – Coreia do Sul", 25, "#0000ff")]
		CoreanoCoreiaDoSul = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Croata – Croácia", 7, "#0000ff")]
		CroataCroCia = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dinamarquês – Dinamarca", 9, "#0000ff")]
		DinamarquSDinamarca = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Eslovaco – Eslováquia", 37, "#0000ff")]
		EslovacoEslovQuia = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Esloveno – Eslovênia", 38, "#0000ff")]
		EslovenoEslovNia = 1060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Espanhol (Tradicional) – Espanha", 39, "#0000ff")]
		EspanholTradicionalEspanha = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Estoniano – Estônia", 12, "#0000ff")]
		EstonianoEstNia = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Finlandês – Finlândia", 13, "#0000ff")]
		FinlandSFinlNdia = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Francês – França", 14, "#0000ff")]
		FrancSFranA = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Galego – Espanha", 15, "#0000ff")]
		GalegoEspanha = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Grego – Grécia", 17, "#0000ff")]
		GregoGrCia = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hebraico", 18, "#0000ff")]
		Hebraico = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Híndi – Índia", 19, "#0000ff")]
		HNdiNdia = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Húngaro – Hungria", 20, "#0000ff")]
		HNgaroHungria = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Holandês – Países Baixos", 10, "#0000ff")]
		HolandSPaSesBaixos = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indonésio – Indonésia", 21, "#0000ff")]
		IndonSioIndonSia = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inglês", 11, "#0000ff")]
		InglS = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Italiano – Itália", 22, "#0000ff")]
		ItalianoItLia = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Japonês – Japão", 23, "#0000ff")]
		JaponSJapO = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Letão – Letônia", 26, "#0000ff")]
		LetOLetNia = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lituano – Lituânia", 27, "#0000ff")]
		LituanoLituNia = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Malaio – Malásia", 28, "#0000ff")]
		MalaioMalSia = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Norueguês (Bokmål) – Noruega", 29, "#0000ff")]
		NorueguSBokmLNoruega = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Polonês – Polônia", 30, "#0000ff")]
		PolonSPolNia = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Português – Brasil", 31, "#0000ff")]
		PortuguSBrasil = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Português – Portugal", 32, "#0000ff")]
		PortuguSPortugal = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Árabe", 0, "#0000ff")]
		Rabe = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Romeno – Romênia", 33, "#0000ff")]
		RomenoRomNia = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Russo – Rússia", 34, "#0000ff")]
		RussoRSsia = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sérvio (Cirílico) – Sérvia", 35, "#0000ff")]
		SRvioCirLicoSRvia = 3098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sérvio (Latino) – Sérvia", 36, "#0000ff")]
		SRvioLatinoSRvia = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sueco – Suécia", 40, "#0000ff")]
		SuecoSuCia = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tailandês – Tailândia", 41, "#0000ff")]
		TailandSTailNdia = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tcheco – República Tcheca", 8, "#0000ff")]
		TchecoRepBlicaTcheca = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Turco – Turquia", 42, "#0000ff")]
		TurcoTurquia = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ucraniano – Ucrânia", 43, "#0000ff")]
		UcranianoUcrNia = 1058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vietnamita – Vietnã", 44, "#0000ff")]
		VietnamitaVietn = 1066,
	}
}
#pragma warning restore CS1591
